const PARAMETER_ATTRIBUTES = 'attrib';
const PARAMETER_PROPERTIES = 'properties';
const PARAMETER_SORT_ORDER = 'order';
const PARAMETER_PAGINATION_ITEMS_PER_PAGE = 'count';
const PARAMETER_PAGINATION_START = 'first';

export default {
    PARAMETER_ATTRIBUTES: PARAMETER_ATTRIBUTES,
    PARAMETER_PROPERTIES: PARAMETER_PROPERTIES,
    PARAMETER_SORT_ORDER: PARAMETER_SORT_ORDER,
    PARAMETER_PAGINATION_ITEMS_PER_PAGE: PARAMETER_PAGINATION_ITEMS_PER_PAGE,
    PARAMETER_PAGINATION_START: PARAMETER_PAGINATION_START
}