const PARAMETER_ATTRIBUTES = 'attrib';
const PARAMETER_PAGE = 'page';
const PARAMETER_SORTING = 'sorting';
const PARAMETER_ITEMS = 'items';

export default {
    PARAMETER_ATTRIBUTES: PARAMETER_ATTRIBUTES,
    PARAMETER_PAGE: PARAMETER_PAGE,
    PARAMETER_SORTING: PARAMETER_SORTING,
    PARAMETER_ITEMS: PARAMETER_ITEMS
}