name: Tests

on: [push]

jobs:
  phpunit:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP with Composer 2
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.1
        coverage: xdebug
        tools: composer:v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install

    - name: Check linting rules
      run: composer lint

    - name: Run tests
      run: composer test

  js-lint-and-test:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Check linting rules
        run: npm run lint

      - name: Run tests
        run: npm run test
